version: '3.8'

services:
  nuxt-app:
    build:
      context: .
    command: npm run dev
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - .:/frontend
      - /frontend/node_modules